### ISSUE TITLE
on zsh have problem

### ISSUE THREAD

**Issue by robbinhan** [mmastrac/iterm2-zmodem#1]
I use zsh ,and I cant transfer something to remote or download. I dont why.Does somebody help?

**Comment by reallovelei** [comment]
Same problem here.

**Comment by frank0718** [comment]
0ive.**B0100000023be50     failed on zsh , how to fix it

**Comment by mmastrac** [comment]
Hi,

I'm forcing escaping of all characters by default now. Please try the latest version and re-open the issue if it still persists.
