### ISSUE TITLE
Support for iTerm2 3.0

### ISSUE THREAD

**Issue by gnachman** [mmastrac/iterm2-zmodem#10]
Easy to fix: just change "iTerm" to "iTerm2" in your applescript.

**Comment by mmastrac** [comment]
Ah thanks. I wonder if I can get AppleScript to fall back to `iTerm` if `iTerm2` isn't found.

**Comment by gnachman** [comment]
Easiest way would be to use osascript to check if someone is responding. For example:

````
osascript -e 'tell application "iTerm2" to version' > /dev/null 2>&1 && NAME=iTerm2 || NAME=iTerm
````

will fail set `NAME` to what you ought to be `tell`ing.

**Comment by mmastrac** [comment]
Gotcha. Will patch this shortly.

**Comment by mmastrac** [comment]
Fixed!
