### ISSUE TITLE
rz and i can't find file

### ISSUE THREAD

**Issue by las1991** [mmastrac/iterm2-zmodem#13]
macos 10.12.2 
iterm2 3.0.13
lrzsz 0.12.20

**Comment by schwt** [comment]
i'am confronted with the same probrem

**Comment by schwt** [comment]
Files can't transfered if the term is logged in using expect script!
changing to ssh in cmd line, it works!

**Comment by cnhao** [comment]
=_=!! find the answer

**Comment by las1991** [comment]
Thanks , it works!

**Comment by dayinfinite** [comment]
Thanks, This is the reason
