### ISSUE TITLE
can not transfer local file to remote centos when using rz

### ISSUE THREAD

**Issue by iamyh** [mmastrac/iterm2-zmodem#18]
I follow the steps:

1:do the steps as READ.md.

2:ssh to cenos server,then rz.

3:items show the files to choose.

4:after choosed,in centos server terminal,it shows "Received....",but when I "ls -tr",it does not find the file

osx version：10.11.4    iterm version:3.0.2

**Comment by iamyh** [comment]
could u help me please?what is the problem?

**Comment by huyanwei00** [comment]
@iamyh ，same problem，have you sloved it？

**Comment by iamyh** [comment]
@huyanwei00 not yet.it seems that the author is not active

**Comment by zuoerlost** [comment]
I get the same problem, rz can't work! some one fix it?

**Comment by starchou** [comment]
problem +1
macOS 10.12.4

**Comment by iamyh** [comment]
i solved this problem.because i used `expect` to ssh to remote server.if i use ssh to remote server,it will be ok~~

**Comment by yuanhuikai** [comment]
+1 it works

**Comment by starchou** [comment]
yeah i had use expect too，

**Comment by Aeternam** [comment]
really appreciate your answer, iamyh.

**Comment by sktoozaki** [comment]
@iamyh Thank you very much!

**Comment by houshunwei** [comment]
Thanks @iamyh

**Comment by ThomasLau** [comment]
Thanks @iamyh this works.
