### ISSUE TITLE
rz can't work?

### ISSUE THREAD

**Issue by zuoerlost** [mmastrac/iterm2-zmodem#19]
macOs 10.12.4, item2 3.0.x 
I do it by the README step , but rz and sz can't work, help me, thx

**Comment by jamslee** [comment]
me too

**Comment by jamslee** [comment]
macOs 10.12.4, item2 3.0.x

**Comment by goldlin** [comment]
In my case, you need to chmod 755 for these 2 file

**Comment by lizijie1993** [comment]
In my case, when I use expect login my remote machine, rz/sz failed. But login without expect, rz/sz successed.

**Comment by pinguo-fengxingchao** [comment]
@lizijie1993 me too.

**Comment by gotodoit** [comment]
@lizijie1993 me too.Have you solved it?

**Comment by lizijie1993** [comment]
@gotodoit @pinguo-fengxingchao 
You could use zssh instead of ssh in you expect script. zssh has a transfer mode, where you can use rz/sz to transfer file.

**Comment by pinguo-fengxingchao** [comment]
@lizijie1993  If I use ZSSH, then the iTerm2 script seems to be useless.

**Comment by johnwangwjq** [comment]
Me too.  The `expect` login broke rz/sz .

**Comment by FashionVon** [comment]
horrible ！I find  expect broke  rz and sz. Why？

**Comment by DvHuang** [comment]
what's the meaning of "expect login"?

**Comment by DvHuang** [comment]
it's amzzing!! it works when don't use the expect login!!!!!
thanks everyone!

**Comment by mmastrac** [comment]
Closing in favour of #25 to track all these bugs

**Comment by neozo** [comment]
Me too. The expect login broke rz/sz .

**Comment by superkzh** [comment]
> In my case, when I use expect login my remote machine, rz/sz failed. But login without expect, rz/sz successed.

Thank you, it wastes a lot of my time.
