### ISSUE TITLE
 Incompatible with GNU Screen?

### ISSUE THREAD

**Issue by hongliang5316** [mmastrac/iterm2-zmodem#20]
When i use `sz filename` inside a `screen` and my iterm2 will be locked quite a time and the operation was unsuccessful. Do you have any suggestions for this, Thanks!

**Comment by drod3763** [comment]
I have a similar issue. I use it to try to upload files to a raspberry pi via the Serial Gadget interface. The `rz` command lets me pick a file but doesn't finish the upload.

**Comment by mmastrac** [comment]
Marking as dupe of #25 to clean up issue tracker.
