### ISSUE TITLE
can not work with 'expect'

### ISSUE THREAD

**Issue by PlayingJoker** [mmastrac/iterm2-zmodem#24]
I'm using a jumpserver for auto connect server, wrote a expect script like this:
```
#!/usr/bin/expect
set password fweFG@#F!FE
set timeout -1

spawn ssh -i ~/Documents/pems/server.pem jump@192.168.6.155
expect "*passphrase*"
send "$password\r"
interact
```
then it can't work anymore.
but can work without expect.

example:
ssh -i ~/Documents/pems/server.pem jump@192.168.6.155
Enter passphrase for key '/Users/joker/Documents/pems/liuzn.pem':

**Comment by ritahunter** [comment]
me too. We write a script to login server using 'expect' without password input. BUT rz, sz will fail. The command will succeed, and can't find the file is... so pls help~

**Comment by fcbruce** [comment]
the same problem met.

**Comment by fcbruce** [comment]
@PlayingJoker @ritahunter Hi, I found the solution that we can use zssh instead of ssh

**Comment by misskeyjoy** [comment]
me to. I debug find the  problem.

**Comment by mmastrac** [comment]
Marking as dupe of #25 to clean up issue tracker.

**Comment by biuge** [comment]
> @playingjoker @ritahunter Hi, I found the solution that we can use zssh instead of ssh

老铁你是怎么做的 我也是zsh下写exp脚本 然后rz失败
