### ISSUE TITLE
compatiblity issue

### ISSUE THREAD

**Issue by russell7** [mmastrac/iterm2-zmodem#3]
client
OS X 10.9.2
iTerm2 Build 1.0.0.20140112
oh-my-zsh https://github.com/robbyrussell/oh-my-zsh/commit/48579ebf2bff8d41cd36f8eae72d526f2a9e1864
lrzsz (installed by brew) stable 0.12.20

this is where iterm2-zmodem installed.
and when I ssh to these servers.

>server A
>centos 6.0
>lrzsz version 0.12.20 Release 27.1.el6
>### works ###

&ensp;
>server B
>debian 7
>lrzsz Version: 0.12.21-5
>### doesn't work###

&ensp;
>server C
>redhat 5.3
>lrzsz version 0.12.20
>### works ###

seems to be lrzsz compatiblity issue, but I'm afraid after I update lrzsz package on OS X, the situation change to this can't work on server A and C.

any suggestion?
thanks in advance.

**Comment by mmastrac** [comment]
I'm forcing escaping of all characters by default now. Please try the latest version and re-open the issue if it still persists.
