### ISSUE TITLE
Some disscusions

### ISSUE THREAD

**Issue by gaofeijin** [mmastrac/iterm2-zmodem#35]
Hello, I'm a programmer from China. In any case , I'd like to thank you for providing this project which exactly solved my problem. Yet still I think your support for a free Taiwan and a free Tibet is quite improper. Here are my reasons. Firstly, this is github, which means we should not let politics involve in. Secondly, the real situation of Taiwan and Tibet is quite complicated. By saying this, I mean you may not know the real situation or be cheated by fake news. If you want me to provide more information, please reply to me and I would have some rational discussion with you. I really hope you can withdraw you support.

**Comment by mmastrac** [comment]
Hi, I don't believe the situation is complicated at all. Please read the english discussions of these topics (including the massacre at https://en.wikipedia.org/wiki/Tiananmen_Square) for more information.

**Comment by gaofeijin** [comment]
Sorry for replying so late, because I'm on a vacation. 

I'm a Chinese. I can read and speak English and I wonder if you could read Chinese. I have various sources of information, domestic and international both. And I think I know much more about my country's history, including the Taiwan part, the Tibet Part, and the Tiananmen Square part.

Everything has its causes. The violent events happened in Tibet is caused by some supporters of Dalai Lama, who wants to restore the aristocracy in Tibet. You can watch this [video](https://www.youtube.com/watch?v=rhQSj796uoU) to learn a bit about what kind of life nomal people lived 70 yeard ago under the aristocracy of Tibet. If you are still concerned, you can travel to Tibet and see by yourself what kind of life Tibetans live now.

The so-called Tiananmen_square massacre is a truth, I admit to that. Innocent and armless young men killed by military, that is a sin and should be accused by any conscientious man. However, just like the Trolley Problem, the leaders of PRC and CPC had to make a choice between kill one and kill more. As a result of what actually happened, the goveronment didn't collapse and maintained a peaceful environment in China, which helped the vast majority of Chinese get wealthier and live better. I don't mean to persuade you to agree with me, but just offer another perspective.

As for Taiwan, this issue has its rather complicated history backgrounds. If you want me to explain it,  I may have to write a PHD thesis. So I suggest that we do not comment on the things we do not fully understand. Take me as an example, I don't understand the history of crusades, so I never judge which part stands for just.

If you still want disscution, I'd like to know more about your views.

**Comment by fudanglp** [comment]
@mmastrac you are biased. I lived in Tianjin besides Beijing. If there is a massacre, can we just ignore it?

**Comment by plantvsbirds** [comment]
> massacre

Your parents probably did

**Comment by plantvsbirds** [comment]
> @mmastrac you are biased. I lived in Tianjin besides Beijing. If there is a massacre, can we just ignore it?

Your parents probably did.

**Comment by mmastrac** [comment]
@fudanglp Try searching for anything about the event on Baidu. Weird how nothing comes up, isn't it? 

> Outside mainland China, and among circles critical of the crackdown within mainland China, it is commonly referred to in Chinese as June Fourth Massacre (Chinese: 六四屠杀, liù-sì túshā) and June Fourth Crackdown (Chinese: 六四镇压, liù-sì zhènyā). To bypass internet censorship in China, which uniformly considers all the above-mentioned names too 'Sensitive' for search engines and public forums, alternative names have sprung up to describe the events on the Internet, such as May 35th, VIIV (Roman numerals for 6 and 4) and Eight Squared (i.e. 82=64).[15]
