### ISSUE TITLE
broken on OS X 10.10.1, iterm 2.0.0.20141103, lrzsz 0.12.20

### ISSUE THREAD

**Issue by ssbarnea** [mmastrac/iterm2-zmodem#6]
I tried to use it to receive a file using OS X 10.10.1, iterm 2.0.0.20141103, lrzsz 0.12.20 and I was prompted to download the file (pick directory) but no file was received.
```
root@xso:/opt/atlassian/jira.new/logs# sz jira-fail-upgrade-from-62to63.tar.gz
�*C�3jira-fail-upgrade-from-62to63.tar.gz47329 12455712206 100644 0 1 47329kJP*C�3jira-fail-upgrade-from-62to63.tar.gz47329 12455712206 100644 0 1 47329kJP*C�3jira-fail-upgrade-from-62to63.tar.gz47329 12455712206 100644 0 1 47329kJP*C�3jira-fail-upgrade-from-62to63.tar.gz47329 12455712206 100644 0 1 47329kJP*C�3jira-fail-upgrade-from-62to63.tar.gz47329 12455712206 100644 0 Press any key to continue...
```
I checked and the file didn't appear locally.

**Comment by seanlei** [comment]
same problem to me 
OS X 10.10.2,iterm 2.0.0.20141103 ,lrzsz0.12.20
after pick directory
no file was received when coprocess finished

**Comment by dolphin-zs** [comment]
I encountered the similar problem too. sz didn't work.

**Comment by GangWang** [comment]
same problem to me 
sz didn't work.
rz   didn't work too.        "z waiting to receive.**B0100000023be50"

**Comment by chestnutchen** [comment]
And is there any resolutions?

**Comment by seanlei** [comment]
not yet

2015-10-30 17:38 GMT+08:00 chestnut <notifications@github.com>:

**Comment by mmastrac** [comment]
Unfortunately I haven't had a chance to look into this for some time. I suspect that I'll have to package a specific version of lszrz with the client, but it is also possible that server-side versions are causing issues.

**Comment by yiisama** [comment]
same problem.
sz works fine, but rz didn't work with large files (for example, 200KB is ok, 2MB failed).
the command line just freezed at "�z waiting to receive.**B0100000023be50"

**Comment by wonderffee** [comment]
Just test sz, same problem to me, OS X 10.10.5, iTerm 2 Build 2.1.4, lrzsz: stable 0.12.20.

**Comment by marsqing** [comment]
It seems lrzsz 0.12.20 change sz to lsz and rz to lrz. Just mofity the two .sh file in this repo and change /usr/local/bin/rz to /usr/local/bin/lrz and /usr/local/bin/sz to /usr/local/bin/lsz. It then works.

**Comment by chestnutchen** [comment]
@marsqing It works fine! Thx~

**Comment by ghostchef** [comment]
please make sure the two .sh files executable, type the following line:
`$sudo chmod 777 /usr/local/bin/iterm2-*`

**Comment by chzju** [comment]
https://github.com/aurora/iterm2-zmodem this script works

**Comment by fanhefan** [comment]
@chzju 
always didn't work~~~   
OS X 0.11.4,iterm  2.1.4
Mac lrzsz stable 0.12.20
Server 0.12.20

**Comment by changbingbing** [comment]
@fanhefan Are you OK?Me too,always didn't work....
OS X 10.11.4,iterm 2.1.4
Mac lrzsz stable 0.12.20
Server 0.12.20

**Comment by fanhefan** [comment]
@changbingbing no~~~

**Comment by chestnutchen** [comment]
https://github.com/chestnutchen/iterm2-zmodem
This works fine for me.

**Comment by fanhefan** [comment]
@chestnutchen i try chestnutchen/iterm2-zmodem,don`t work too....

**Comment by iyaozhen** [comment]
When I update iterm2 to `Build 3.0.0`, yesterday. `rz` can't work, always alert file choose window and can't cancel. `sz` work well.

**Comment by mmastrac** [comment]
Hi all,

I've updated the scripts to support iTerm2 v3, as well as forcing auto-escape. Please try the latest version and re-open a new issue if it is still broken.

**Comment by fanhefan** [comment]
[root@AY140108171721776a78Z wwwlogs]# rz
rz waiting to receive.**B0100000023be50
[root@AY140108171721776a78Z wwwlogs]# # Received /Users/cocos/Downloads/hehe.pdf
i can't find upload file

[root@08171721776a78Z /]# sz MD5_Cofig.ini
**B00000000000000
[root@08171721776a78Z /]# # Sent -> /Users/cocos/Desktop/
i can't find download file

**Comment by mmastrac** [comment]
@fanhefan Is there information you can provide to help diagnose this?

 - Which version of OSX?
 - Which version of lrzsz (server and client)?
 - Are you using tmux or any other multiplexer?

Do you see the "coprocess" indicators running when the transfer begins?

**Comment by fanhefan** [comment]
- osx 10.11.4
- client version 0.12.20 , server version 0.12.20
- no

 How can i see the "coprocess" indicators running?

**Comment by Medusar** [comment]
@mmastrac hi my OSX version is 10.11.6 and  iterm2 is version 3.0

**Comment by Haoning** [comment]
rz is not working under Mac OS X 10.13.1 when copying binary data with "rz -e", the select window popup, but when choosing a binary file, it hangs.
iTerm2 Build 3.1.5, I tried 3.0.0, it also doesn't work.

**Comment by wdfnst** [comment]
I have solved this problem, do like this:
1. Check and delete the while space embrace "Regular Expression" when configure the triggers in profiles--> Advance;
2. Check and copy the sz/rz file:  cp /usr/local/bin/sz /usr/local/bin/ and rz
3. Then enjoy....

**Comment by fangjingping** [comment]
why not choose FinalShell ? it's great i think.
